# =============================================
# SIRF LOCAL USE KE LIYE — GitHub pe PUSH MAT KARNA
# Ye file .gitignore mein already blocked hai
# =============================================
 

[mongodb]
uri = "mongodb+srv://tripuser:DX9YrBEzfGrE6vt9@cluster0.m0mszxn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
database = "trip_db"
 